### PR TITLE
Extension storage

### PR DESCRIPTION
**Pull request by GarboMuffin**
There are two kinds of storage:

 - per-project: `runtime.extensionStorage[id]`, for global things
 - per-sprite: `target.extensionStorage[id]`, for things that may vary for each sprite

(note that this is a different metaphor than what Scratch uses for variables, where global variables are stored on the stage which itself just a sprite)

both are saved in project.json (or sprite.json, when exporting a single sprite) and thus must be any JSON-serializable value

to clear the data, use the `delete` operator or set the data to null/undefined

you are intended to index into extensionStorage with your extension's id; if you don't then your data won't be saved (it removes unused extensions)

### CODE REVIEW

**Comment by GarboMuffin** [comment]
currently there are no helper methods, it's just a raw object you can read and write to. that can change if you want (eg. getOrDefault())

**Comment by LilyMakesThings** [comment]
This is precisely what I'm after

**Comment by yuri-kiss** [comment]
same

**Comment by GarboMuffin** [comment]
nobody quite answered whether they want any helpers so i assume you dont

**Comment by yuri-kiss** [comment]
> nobody quite answered whether they want any helpers so i assume you dont

poop, yeah we forgot

**Comment by LilyMakesThings** [comment]
i'm good without helpers so it ain't a big deal

**Pull request merged**
