### PR TITLE
Add vm.exports.i_will_not_ask_for_help_when_these_break

### PR DESCRIPTION
**Pull request by GarboMuffin**

### CODE REVIEW

**Comment by GarboMuffin** [comment]
what else is wanted

**Comment by yuri-kiss** [comment]
can u squeeze them in plssss

**Comment by yuri-kiss** [comment]
also could we have the input types like ConstantInput and so on?

(I should probally be more specific)
ConstantInput, TypedInput, Frame (all in JSGen) and jsexecute

**Comment by LilyMakesThings** [comment]
this is the funniest export i've ever seen

**Comment by yuri-kiss** [comment]
> this is the funniest export i've ever seen

DONT TELL HIM THATTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

**Comment by LilyMakesThings** [comment]
> > this is the funniest export i've ever seen
> 
> DONT TELL HIM THATTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

OH GOODNESS
image

**Comment by GarboMuffin** [comment]
the name isn't a joke, it is very serious

*when* these break, you will not be getting any help

**Comment by yuri-kiss** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeee, i hope u do merge this lol

**Comment by yuri-kiss** [comment]
yay :D (edit: HE MERGED 🥳 )

**Pull request merged**
