### PR TITLE
Allow us to get mouse wheel deltaY from ioQuery

### PR DESCRIPTION
**Pull request by LilyMakesThings**

### CODE REVIEW

**Comment by GarboMuffin** [comment]
are you not able to add your own listener scroll event listener to the document?

**Comment by LilyMakesThings** [comment]
I could do that, I just believe it would make more sense to incorporate it in to the vm, no?

**Comment by GarboMuffin** [comment]
at some point you may eventually want to do things like:

 - get horizontal scrolling
 - when mouse scrolled

at which point having your own event listener will be a better approach

**Comment by LilyMakesThings** [comment]
> at some point you may eventually want to do things like:
> 
> * get horizontal scrolling
> * when mouse scrolled
> 
> at which point having your own event listener will be a better approach

Alright, this makes sense

**Pull request closed without merging**
