### PR TITLE
BlockType.XML

### PR DESCRIPTION
**Pull request by GarboMuffin**
For things like https://github.com/TurboWarp/extensions/pull/510

Need to write tests still

Perhaps forbid sandboxed extensions from using this

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
:OO

**Comment by LilyMakesThings** [comment]
How would this be formatted into the blocks[] of an extension?

**Comment by GarboMuffin** [comment]
```js
   blockType: Scratch.BlockType.XML,
   xml: '...'
```

**Comment by yuri-kiss** [comment]
yes

**Comment by yuri-kiss** [comment]
very much needed

**Comment by LilyMakesThings** [comment]
Will you consider putting this on an experiments url?

**Comment by yuri-kiss** [comment]
> Will you consider putting this on an experiments url?

this is a awesome idea

**Comment by yuri-kiss** [comment]
Woohooo!

**Pull request merged**
