### PR TITLE
Implement LOOP and CONDITION blocks in interpreter and compiler

### PR DESCRIPTION
**Pull request by GarboMuffin**
Supercedes https://github.com/TurboWarp/scratch-vm/pull/141

### CODE REVIEW

**Comment by LilyMakesThings** [comment]
let me guess, more lines of tests than actual commits?

**Comment by GarboMuffin** [comment]
pretty close if not

**Comment by GarboMuffin** [comment]
also there's a menu with acceptReporters: false to reconsider

**Comment by LilyMakesThings** [comment]
> also there's a menu with acceptReporters: false to reconsider

elaborate?

**Comment by GarboMuffin** [comment]
wrong pull request

**Pull request merged**
