### PR TITLE
Add `branchIconURI`

### PR DESCRIPTION
**Pull request by CubesterYT**
### Proposed Changes

Adds a new option to blocks called `branchIcon`. This option allows you to add a custom branch icon to a block. This does not have to strictly be a `Scratch.BlockType.LOOP` Block, which makes it all the better. Should work flawlessly with data uri's. 

### Reason for Changes

I added this option because it'll be really useful to have custom branch indications, and also use it in normal blocks as well to indicate anything else.

### Test Coverage

Tried building my own gui, but my node version is too new. So I could not test this, but it should still easily work.

**Edit**
 - Tested by @Ashimee and @JeremyGamer13, works perfectly.

### Example

```js
blocks: [
          {
            opcode: "block",
            text: "block: [ARGUMENT]",
            blockType: Scratch.BlockType.LOOP, // Can be any other block, too, which is fire
            branchIcon: // This is the new option I'm adding. You can specify a data uri here.
            arguments: {
              ARGUMENT: {
                type: Scratch.ArgumentType.STRING
              }
            }
          }
        ],
```
### Potential Changes

Might change it from it's `else if` state and separate it to it's own `if` statement if we want to make the `branchIcon` option also work on `Scratch.BlockType.REPORTER` and `Scratch.BlockType.BOOLEAN`, but I might not do this.

### CODE REVIEW

**Comment by yuri-kiss** [comment]
we need this for shrek icons

**Comment by LilyMakesThings** [comment]
Today is a good day

**Comment by CubesterYT** [comment]
> Today is a good day

@LilyMakesThings, for real

**Comment by yuri-kiss** [comment]
holy poop, you did it :D

**Comment by CubesterYT** [comment]
> holy poop, you did it :D

@Ashimee, YEA I DID

**Pull request merged**
